// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: unistream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UniStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UniStreamRequest) Reset() {
	*x = UniStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unistream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniStreamRequest) ProtoMessage() {}

func (x *UniStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unistream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniStreamRequest.ProtoReflect.Descriptor instead.
func (*UniStreamRequest) Descriptor() ([]byte, []int) {
	return file_unistream_proto_rawDescGZIP(), []int{0}
}

func (x *UniStreamRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UniStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []byte `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *UniStreamResponse) Reset() {
	*x = UniStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unistream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniStreamResponse) ProtoMessage() {}

func (x *UniStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unistream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniStreamResponse.ProtoReflect.Descriptor instead.
func (*UniStreamResponse) Descriptor() ([]byte, []int) {
	return file_unistream_proto_rawDescGZIP(), []int{1}
}

func (x *UniStreamResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_unistream_proto protoreflect.FileDescriptor

var file_unistream_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x75, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x26, 0x0a, 0x10,
	0x55, 0x6e, 0x69, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x11, 0x55, 0x6e, 0x69, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x60, 0x0a, 0x10, 0x75, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x2e, 0x75, 0x6e, 0x69, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x2e, 0x55, 0x6e, 0x69, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x75, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x2e, 0x55, 0x6e, 0x69, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x73, 0x77, 0x61, 0x61, 0x6d,
	0x6d, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x75,
	0x6e, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unistream_proto_rawDescOnce sync.Once
	file_unistream_proto_rawDescData = file_unistream_proto_rawDesc
)

func file_unistream_proto_rawDescGZIP() []byte {
	file_unistream_proto_rawDescOnce.Do(func() {
		file_unistream_proto_rawDescData = protoimpl.X.CompressGZIP(file_unistream_proto_rawDescData)
	})
	return file_unistream_proto_rawDescData
}

var file_unistream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_unistream_proto_goTypes = []interface{}{
	(*UniStreamRequest)(nil),  // 0: unistream.UniStreamRequest
	(*UniStreamResponse)(nil), // 1: unistream.UniStreamResponse
}
var file_unistream_proto_depIdxs = []int32{
	0, // 0: unistream.unistreamService.SendMessage:input_type -> unistream.UniStreamRequest
	1, // 1: unistream.unistreamService.SendMessage:output_type -> unistream.UniStreamResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_unistream_proto_init() }
func file_unistream_proto_init() {
	if File_unistream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unistream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unistream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unistream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unistream_proto_goTypes,
		DependencyIndexes: file_unistream_proto_depIdxs,
		MessageInfos:      file_unistream_proto_msgTypes,
	}.Build()
	File_unistream_proto = out.File
	file_unistream_proto_rawDesc = nil
	file_unistream_proto_goTypes = nil
	file_unistream_proto_depIdxs = nil
}
